-- ==========================================================
-- DataSense AI - Supabase Database Schema
-- Multi-Agent Autonomous Data Investigation Platform
-- ==========================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Datasets Table: Stores uploaded dataset metadata and storage locations
CREATE TABLE IF NOT EXISTS public.datasets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID, -- Optional user association (can be NULL for guest/hackathon demo)
    name VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_path TEXT NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    file_format VARCHAR(32) NOT NULL DEFAULT 'csv',
    row_count INTEGER,
    column_count INTEGER,
    schema_metadata JSONB DEFAULT '{}'::jsonb, -- Column names, detected types, null counts
    health_score NUMERIC(5, 2), -- 0.00 to 100.00
    status VARCHAR(50) DEFAULT 'uploaded', -- uploaded, processing, completed, error
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Investigation Jobs Table: Tracks pipeline orchestration state across 8 agents
CREATE TABLE IF NOT EXISTS public.investigation_jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    dataset_id UUID NOT NULL REFERENCES public.datasets(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'queued', -- queued, running, completed, failed
    current_agent VARCHAR(64), -- Detective, Inspector, Cleaner, Planner, Scientist, Architect, Analyst, FactChecker
    progress_percentage INTEGER DEFAULT 0,
    health_score NUMERIC(5, 2),
    summary TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Agent Execution Logs: Real-time telemetry displayed on the Frontend Agent Timeline
CREATE TABLE IF NOT EXISTS public.agent_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID NOT NULL REFERENCES public.investigation_jobs(id) ON DELETE CASCADE,
    agent_name VARCHAR(64) NOT NULL,
    agent_icon VARCHAR(16), -- 🔍, 🩺, 🧹, 🧠, 🤖, 📊, 💡, ✅
    step_title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'in_progress', -- in_progress, completed, warning, failed
    details JSONB DEFAULT '{}'::jsonb,
    duration_ms INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Investigation Plans: Generated by Agent 4 (Investigation Planner)
CREATE TABLE IF NOT EXISTS public.investigation_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID NOT NULL REFERENCES public.investigation_jobs(id) ON DELETE CASCADE,
    objectives JSONB NOT NULL DEFAULT '[]'::jsonb, -- List of planned hypotheses/questions
    priority_columns JSONB DEFAULT '[]'::jsonb,
    rationale TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ML & Statistical Artifacts: Generated by Agent 5 (Data Scientist Agent)
CREATE TABLE IF NOT EXISTS public.ml_artifacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID NOT NULL REFERENCES public.investigation_jobs(id) ON DELETE CASCADE,
    analysis_type VARCHAR(64) NOT NULL, -- correlation, outliers, clusters, distributions, trends
    parameters JSONB DEFAULT '{}'::jsonb,
    results_data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Dashboard Configurations: Generated by Agent 6 (Visualization Architect)
CREATE TABLE IF NOT EXISTS public.dashboard_configs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID NOT NULL REFERENCES public.investigation_jobs(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    layout_grid JSONB NOT NULL DEFAULT '[]'::jsonb, -- Grid placement configurations
    charts JSONB NOT NULL DEFAULT '[]'::jsonb, -- Plotly chart specs with reasons for choice
    summary_metrics JSONB NOT NULL DEFAULT '[]'::jsonb, -- KPI cards
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Verified Insights & Fact-Checks: Generated by Agent 7 & 8 (Insight Analyst & Fact Checker)
CREATE TABLE IF NOT EXISTS public.insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID NOT NULL REFERENCES public.investigation_jobs(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(64) DEFAULT 'trend', -- trend, anomaly, correlation, cluster, data_quality
    importance VARCHAR(32) DEFAULT 'medium', -- high, medium, low
    related_chart_id VARCHAR(64),
    related_columns JSONB DEFAULT '[]'::jsonb,
    is_verified BOOLEAN DEFAULT FALSE,
    fact_check_verdict VARCHAR(32) DEFAULT 'pending', -- verified, modified, rejected, pending
    fact_check_notes TEXT,
    underlying_metrics JSONB DEFAULT '{}'::jsonb, -- Exact mathematical proof/facts
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_investigation_jobs_dataset_id ON public.investigation_jobs(dataset_id);
CREATE INDEX IF NOT EXISTS idx_agent_logs_job_id ON public.agent_logs(job_id);
CREATE INDEX IF NOT EXISTS idx_insights_job_id ON public.insights(job_id);
CREATE INDEX IF NOT EXISTS idx_ml_artifacts_job_id ON public.ml_artifacts(job_id);

-- Storage buckets configuration (can be run in Supabase SQL editor):
-- INSERT INTO storage.buckets (id, name, public) VALUES ('datasets', 'datasets', true) ON CONFLICT DO NOTHING;
-- INSERT INTO storage.buckets (id, name, public) VALUES ('exports', 'exports', true) ON CONFLICT DO NOTHING;
